server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: projects-service
          uri: lb://PROJECTS-SERVICE
          predicates:
            - Path=/api/projects/**
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/**
        - id: financial-service
          uri: lb://FINANCIAL-SERVICE
          predicates:
            - Path=/financial/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Fixed URL
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG